/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NmapTutor;

/**
 *
 * @author work
 */
public class Instructions extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Instructions() {
        initComponents();
      //  setExtendedState(MAXIMIZED_BOTH); // This code opens the applicaiton in full screen //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Instructionslabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Homemenu = new javax.swing.JMenu();
        Instructionsmenu = new javax.swing.JMenu();
        NMAPmenu = new javax.swing.JMenu();
        Riskmenu = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        Instructionslabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Instructionslabel.setText("Instructions");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Step 1\n\nGo to the NMAP page which is located in the top left of the application\nlook over the different quesitons and have a couple of minutes to think of what they mean ?\nhow could they be used ?\n\nStep 2\n\nClick the \"reveal\" button to see what the answer is to the command that you're trying to learn. \nOnce you feel happy that you know all of the commands move on to step 3\n\nstep3 \n\nGo to the Nmap tool and do a scan of the network with the commands you have learnt (make sure you have permission to do so first).\nOnce you feel comfortable with Nmap come back to Nmap tutor and input the data into the first table on the risk assessment page.\n\nNext navigate to the second table below and use the API feature that shows the different CVE's out there . \n\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        Homemenu.setText("Home");
        Homemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomemenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Homemenu);

        Instructionsmenu.setText("Instructions");
        Instructionsmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructionsmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Instructionsmenu);

        NMAPmenu.setText("NMAP");
        NMAPmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NMAPmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(NMAPmenu);

        Riskmenu.setText("Risk assessment");
        Riskmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiskmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Riskmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Instructionslabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Instructionslabel, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        setSize(new java.awt.Dimension(722, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InstructionsmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructionsmenuMouseClicked
        // TODO add your handling code here:

     
 Instructions s = new Instructions();
                s.setVisible(true);
                
                
                  dispose();
                Instructions ul =new Instructions();
                ul.setVisible(false);
        
        
    }//GEN-LAST:event_InstructionsmenuMouseClicked

    private void HomemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomemenuMouseClicked
        // TODO add your handling code here:
        
        
        
         Home s = new Home();
                s.setVisible(true);
                
                
                  dispose();
                Home ul =new Home();
                ul.setVisible(false);
    }//GEN-LAST:event_HomemenuMouseClicked

    private void RiskmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiskmenuMouseClicked
        // TODO add your handling code here:
        
        
        Riskassessment s = new Riskassessment();
                s.setVisible(true);
                
                
                  dispose();
                Riskassessment ul =new Riskassessment();
                ul.setVisible(false);
    }//GEN-LAST:event_RiskmenuMouseClicked

    private void NMAPmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMAPmenuMouseClicked


Nmap s = new Nmap();
                s.setVisible(true);
                
                
                  dispose();
                Nmap ul =new Nmap();
                ul.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_NMAPmenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Homemenu;
    private javax.swing.JLabel Instructionslabel;
    private javax.swing.JMenu Instructionsmenu;
    private javax.swing.JMenu NMAPmenu;
    private javax.swing.JMenu Riskmenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
