/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NmapTutor;
import java.awt.Window;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author work
 */
public class Nmap extends javax.swing.JFrame {

   Connection conlookup = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
 DefaultTableModel defaultTableModel = new DefaultTableModel();
 
 
 
 
    /**
     * 
     * 
     * 
     * Creates new form Home
     */
    public Nmap() {
        initComponents();
       conlookup = DBConnection.ConnectionDB();
        
      setLocationRelativeTo(null);
      Object columns[] = {"Host"};
        defaultTableModel.setColumnIdentifiers(columns);
      
        
        
        
        t5answer.setVisible(false);
        
        scriptanswer.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svsubmit = new javax.swing.JButton();
        psubmit = new javax.swing.JButton();
        t5submit = new javax.swing.JButton();
        scriptsubmit = new javax.swing.JButton();
        scriptquestion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t5answer = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        scriptanswer = new javax.swing.JTextArea();
        svquestion = new javax.swing.JTextField();
        pquestion = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        svanswer = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        panswer = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Homemenu = new javax.swing.JMenu();
        faqsub = new javax.swing.JMenuItem();
        Instructionsmenu = new javax.swing.JMenu();
        NMAPmenu = new javax.swing.JMenu();
        Riskmenu = new javax.swing.JMenu();

        svsubmit.setText("Reveal anwser ");
        svsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svsubmitMouseClicked(evt);
            }
        });
        svsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svsubmitActionPerformed(evt);
            }
        });

        psubmit.setText("Reveal anwser ");
        psubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psubmitMouseClicked(evt);
            }
        });
        psubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psubmitActionPerformed(evt);
            }
        });

        t5submit.setText("Reveal anwser ");
        t5submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5submitActionPerformed(evt);
            }
        });

        scriptsubmit.setText("Reveal anwser ");
        scriptsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptsubmitActionPerformed(evt);
            }
        });

        scriptquestion.setEditable(false);
        scriptquestion.setText("Can you run scripts in NMAP ?");
        scriptquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptquestionActionPerformed(evt);
            }
        });

        t5answer.setEditable(false);
        t5answer.setColumns(20);
        t5answer.setRows(5);
        t5answer.setText("This command allows the user to speed up their scans\nto the maximum speed allowed in NMAP . It requires a \nfast network though. The exmaple for this is \n192.168.20.1 -T5");
        jScrollPane1.setViewportView(t5answer);

        scriptanswer.setEditable(false);
        scriptanswer.setColumns(20);
        scriptanswer.setRows(5);
        scriptanswer.setText("Yes you can !  Scripts alllow you to many different things \nwithin NMAP , and one exmaple of this is  an ftp brute force check\nnmap --script ftp-brute -p 21 <host>");
        jScrollPane5.setViewportView(scriptanswer);

        svquestion.setEditable(false);
        svquestion.setText("What does the -sV command do in NMAP ?");

        pquestion.setEditable(false);
        pquestion.setText("What does the -p command do in NMAP ?");
        pquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pquestionActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setText("What does the -T5 command do in NMAP ?");

        svanswer.setEditable(false);
        svanswer.setColumns(20);
        svanswer.setRows(5);
        svanswer.setText("The -Sv command shows what services are running on the\nnetwork . \nAn example of this is 192.168.20.1 -sV");
        jScrollPane2.setViewportView(svanswer);

        panswer.setEditable(false);
        panswer.setColumns(20);
        panswer.setRows(5);
        panswer.setText("The -p command allows the user to scan a specfic Ip or \nsubnet for a specfic port .\nAn example of this could be 192.168.20.1 -p 21");
        jScrollPane3.setViewportView(panswer);

        Homemenu.setText("Home");
        Homemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomemenuMouseClicked(evt);
            }
        });

        faqsub.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        faqsub.setText("FAQ");
        faqsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faqsubActionPerformed(evt);
            }
        });
        faqsub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                faqsubKeyPressed(evt);
            }
        });
        Homemenu.add(faqsub);

        jMenuBar1.add(Homemenu);

        Instructionsmenu.setText("Instructions");
        Instructionsmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructionsmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Instructionsmenu);

        NMAPmenu.setText("NMAP");
        NMAPmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NMAPmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(NMAPmenu);

        Riskmenu.setText("Risk assessment");
        Riskmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiskmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Riskmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(t5submit)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scriptquestion)
                                .addGap(10, 10, 10)
                                .addComponent(scriptsubmit)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane5)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(svquestion)
                                .addGap(10, 10, 10)
                                .addComponent(svsubmit)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pquestion)
                                .addGap(10, 10, 10)
                                .addComponent(psubmit)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(svquestion)
                                .addGap(3, 3, 3))
                            .addComponent(svsubmit))
                        .addGap(27, 27, 27)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pquestion)
                                .addGap(3, 3, 3))
                            .addComponent(psubmit))
                        .addGap(17, 17, 17)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4)
                                .addGap(3, 3, 3))
                            .addComponent(t5submit))
                        .addGap(37, 37, 37)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scriptquestion)
                                .addGap(3, 3, 3))
                            .addComponent(scriptsubmit))
                        .addGap(37, 37, 37)))
                .addGap(39, 39, 39))
        );

        setSize(new java.awt.Dimension(726, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomemenuMouseClicked
        // TODO add your handling code here:
        
        
        
          Nmap s = new Nmap();
                s.setVisible(true);
                
                
                  dispose();
                Nmap ul =new Nmap();
                ul.setVisible(false);
    }//GEN-LAST:event_HomemenuMouseClicked

    private void InstructionsmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructionsmenuMouseClicked
        // TODO add your handling code here:
        
        
         Instructions s = new Instructions();
                s.setVisible(true);
                
                
                  dispose();
                Instructions ul =new Instructions();
                ul.setVisible(false);
    }//GEN-LAST:event_InstructionsmenuMouseClicked

    private void RiskmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiskmenuMouseClicked
        // TODO add your handling code here:
        
        
        Riskassessment s = new Riskassessment();
                s.setVisible(true);
                
                
                  dispose();
                Riskassessment ul =new Riskassessment();
                ul.setVisible(false);
    }//GEN-LAST:event_RiskmenuMouseClicked

    private void faqsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faqsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faqsubActionPerformed

    private void faqsubKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faqsubKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_faqsubKeyPressed

    private void NMAPmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMAPmenuMouseClicked

 Nmap s = new Nmap();
                s.setVisible(true);
                
                
                  dispose();
                Nmap ul =new Nmap();
                ul.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_NMAPmenuMouseClicked

    private void svsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svsubmitActionPerformed
        // TODO add your handling code here:
        
       
          if (svsubmit.getText()=="Hide"){
            
            svanswer.setVisible(false);   
            
            
            svsubmit.setText("Show");
        }else{
            
            svanswer.setVisible(true);
            svsubmit.setText("Hide");
            
        }
           
        
    }//GEN-LAST:event_svsubmitActionPerformed

    private void psubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psubmitActionPerformed
        // TODO add your handling code here:
        
        
     
          if (psubmit.getText()=="Hide"){
            
            panswer.setVisible(false);   
            
            
            psubmit.setText("Show");
        }else{
            
            panswer.setVisible(true);
            psubmit.setText("Hide");
            
        }
           
    }//GEN-LAST:event_psubmitActionPerformed

    private void t5submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5submitActionPerformed

          if (t5submit.getText()=="Hide"){
            
            t5answer.setVisible(false);   
            
            
            t5submit.setText("Show");
        }else{
            
            t5answer.setVisible(true);
            t5submit.setText("Hide");
            
        }
                   // TODO add your handling code here:
    }//GEN-LAST:event_t5submitActionPerformed

    private void scriptsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptsubmitActionPerformed
        // TODO add your handling code here:
        
        
    
          if (scriptsubmit.getText()=="Hide"){
            
            scriptanswer.setVisible(false);   
            
            
            scriptsubmit.setText("Show");
        }else{
            
            scriptanswer.setVisible(true);
            scriptsubmit.setText("Hide");
            
        }
    }//GEN-LAST:event_scriptsubmitActionPerformed

    private void svsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svsubmitMouseClicked


     
    }//GEN-LAST:event_svsubmitMouseClicked

    private void psubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psubmitMouseClicked

       // conlookup = DBConnection.ConnectionDB();
       // if (conlookup != null){
           // String sql = "SELECT Host FROM Accounts";
           // try{
           // pst = conlookup.prepareStatement(sql);
          //  rs = pst.executeQuery();
           // Object[] columnData = new Object[10];
           // while(rs.next()){
            //    columnData[0] = rs.getString("Host");
              
                 
             
               
              //  defaultTableModel.addRow(columnData);
                

           // }    
           // }catch (Exception e){
                //    JOptionPane.showMessageDialog(null, e);
                    
                    
           // }
       // }
            
          


      
    }//GEN-LAST:event_psubmitMouseClicked

    private void pquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pquestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pquestionActionPerformed

    private void scriptquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptquestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scriptquestionActionPerformed


       
   
    
    
    
    public void loadlookup(){
      
       
       
    
       
      
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nmap().setVisible(true);
            }
        });
        
        
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Homemenu;
    private javax.swing.JMenu Instructionsmenu;
    private javax.swing.JMenu NMAPmenu;
    private javax.swing.JMenu Riskmenu;
    private javax.swing.JMenuItem faqsub;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea panswer;
    private javax.swing.JTextField pquestion;
    private javax.swing.JButton psubmit;
    private javax.swing.JTextArea scriptanswer;
    private javax.swing.JTextField scriptquestion;
    private javax.swing.JButton scriptsubmit;
    private javax.swing.JTextArea svanswer;
    private javax.swing.JTextField svquestion;
    private javax.swing.JButton svsubmit;
    private javax.swing.JTextArea t5answer;
    private javax.swing.JButton t5submit;
    // End of variables declaration//GEN-END:variables
}
